redis: &redis
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: zoneMan

production: *redis
staging: *redis
development: *redis
test: *redis

development:
  adapter: redis
  url: redis://127.0.0.1:6379/1
